#!/bin/bash

src_dir=`pwd`
cd
rm -f .vimrc
rm -fr .vim
rm -f .gvimrc
rm -r .latexmkrc

# 创建符号链接
cd ${src_dir}
ln -s ${src_dir}/vimrc ~/.vimrc
ln -s ${src_dir}/vim ~/.vim
ln -s ${src_dir}/gvimrc ~/.gvimrc
ln -s ${src_dir}/latexmkrc ~/.latexmkrc

vim +PluginInstall +qall

cd ${src_dir}/vim/bundle/YouCompleteMe
git submodule update --init --recursive

# fix the problem 
# CMake Error: The source directory
# "${src_dir}/vim/bundle/YouCompleteMe/third_party/ycmd/third_party/cregex"
# does not appear to contain CMakeLists.txt.

cd ${src_dir}/vim/bundle/YouCompleteMe/third_party/ycmd/third_party 
rm -fr cregex
git submodule update --init --recursive

# compile the YouCompleteMe
cd ${src_dir}/vim/bundle/YouCompleteMe
python3 ./install.py --clang-completer --clangd-completer

